import { mask } from "@common/game/physics";
import { pairList, repeat } from "@common/general/helpers";
import { pos } from "@common/math/geometry";
import type { StadiumSchema } from "@common/stadium-generator";
import type { StadiumObject } from "@haxball/stadium";
import {
    anchorsFromPairs,
    jointsFromPairs,
    line,
    pairedIndexes,
    vLine,
} from "@common/stadium-generator/utils";

const YARD_LINE_BASE = {
    yStart: -266,
    yEnd: 266,
    vertex: { cMask: [] },
};

const YARD_LINE_WHITE = {
    extend: YARD_LINE_BASE,
    segment: { color: "FFFFFF", cMask: [] },
};

const YARD_LINE_RED = {
    extend: YARD_LINE_BASE,
    segment: { color: "D0312D", cMask: [] },
};

const YARD_LINE_YELLOW = {
    extend: YARD_LINE_BASE,
    segment: { color: "FFEA00", cMask: [] },
};

const YARD_LINE_GREEN = {
    extend: YARD_LINE_BASE,
    segment: { color: "ACDE97", cMask: [] },
};

const HASH_MARK_BASE = {
    segment: { color: "FFFFFF", cMask: [] },
    vertex: { cMask: [] },
};

const HASH_MARK_TOP_BASE = { extend: HASH_MARK_BASE, yStart: 80, yEnd: 60 };

const HASH_MARK_BOTTOM_BASE = {
    extend: HASH_MARK_BASE,
    yStart: -60,
    yEnd: -80,
};

const TICK_MARK_BASE = {
    segment: { color: "FFFFFF", cMask: [] },
    vertex: { cMask: [] },
};

const TICK_MARK_TOP_BASE = {
    extend: TICK_MARK_BASE,
    yStart: 266,
    yEnd: 241,
};

const TICK_MARK_BOTTOM_BASE = {
    extend: TICK_MARK_BASE,
    yStart: -241,
    yEnd: -266,
};

const TICK_MARK_GREEN_SEGMENT = {
    segment: { color: "C7E6BD", cMask: [] },
};

const COLLISION_MIDLINE_BASE = {
    segment: {
        vis: false,
        bCoef: 0.1,
        cMask: mask("red", "blue"),
        cGroup: [],
    },
    from: { vertex: { bCoef: 0.1, cMask: mask("red", "blue") } },
    to: { vertex: { bCoef: 0.1, cMask: mask("red", "blue") } },
};

const COLLISION_SIDELINE_BASE = {
    segment: {
        vis: false,
        color: "FFEA00",
        bCoef: 0.1,
        cMask: mask("red", "blue"),
        cGroup: [],
    },
    vertex: { cMask: [] },
    yStart: -375,
    yEnd: 375,
};

const GOAL_POST_SEGMENT = { color: "FFEA00", cMask: [] };
const GOAL_POST_VERTEX = { cMask: [] };
const GOAL_POST_VERTICAL_BASE = {
    segment: GOAL_POST_SEGMENT,
    vertex: GOAL_POST_VERTEX,
    yStart: -60,
    yEnd: 60,
};
const GOAL_POST_LINE_BASE = {
    segment: GOAL_POST_SEGMENT,
    from: { vertex: GOAL_POST_VERTEX },
    to: { vertex: GOAL_POST_VERTEX },
};
const BALL_BOUNDARY_BASE = {
    yStart: 360,
    yEnd: -360,
    segment: { vis: false, cMask: mask("ball") },
};
const BALL_BOUNDARY_LEFT_BASE = {
    extend: BALL_BOUNDARY_BASE,
    segment: { color: "0000FF" },
};
const BALL_BOUNDARY_RIGHT_BASE = {
    extend: BALL_BOUNDARY_BASE,
    segment: { color: "D0312D" },
};

export const classicStadiumSchema = {
    name: "BFL (Classic)",
    canBeStored: false,
    width: 1090,
    height: 395,
    bg: {
        type: "grass",
        width: 930,
        height: 266,
    },
    goals: [
        {
            p0: [-1065, 0],
            p1: [-1005, 0],
            team: "blue",
        },
        {
            p0: [1006.9833374023, 1.6000061035156],
            p1: [1063.9833374023, 1.6000061035156],
            team: "red",
        },
    ],
    playerPhysics: {
        bCoef: 0.5,
        invMass: 1e26,
        kickStrength: 7,
    },
    ballPhysics: {
        radius: 7.125,
        bCoef: 0.5,
        cMask: ["red", "blue", "wall"],
        color: "631515",
        cGroup: ["ball", "kick", "score"],
    },
    cameraFollow: "player",
    spawnDistance: 980,
    traits: {},
    redSpawnPoints: [],
    blueSpawnPoints: [],
    rects: [
        {
            name: "fieldBounds",
            x: [-930, 930],
            y: [-266, 266],
            segment: { color: "FFFFFF", cMask: [] },
            vertex: { cMask: [] },
        },
    ],
    lines: [
        line({
            extend: COLLISION_MIDLINE_BASE,
            from: { x: 0, y: 334 },
            to: { x: 0, y: -330 },
            name: "midfieldCollision",
        }),
        vLine({
            extend: COLLISION_SIDELINE_BASE,
            x: -775,
        }),
        vLine({
            extend: COLLISION_SIDELINE_BASE,
            x: 775,
        }),
        vLine({
            extend: YARD_LINE_YELLOW,
            x: -775,
            name: "leftGoalLine",
        }),
        vLine({
            extend: YARD_LINE_WHITE,
            x: -620,
        }),
        vLine({
            extend: YARD_LINE_RED,
            x: -465,
        }),
        vLine({
            extend: YARD_LINE_WHITE,
            x: -310,
        }),
        vLine({
            extend: YARD_LINE_WHITE,
            x: -155,
        }),
        vLine({
            extend: YARD_LINE_WHITE,
            x: 155,
        }),
        vLine({
            extend: YARD_LINE_WHITE,
            x: 310,
        }),
        vLine({
            extend: YARD_LINE_RED,
            x: 465,
        }),
        vLine({
            extend: YARD_LINE_WHITE,
            x: 620,
        }),
        vLine({
            extend: YARD_LINE_YELLOW,
            x: 775,
            name: "rightGoalLine",
        }),
        vLine({
            extend: YARD_LINE_GREEN,
            x: 0,
            name: "midfieldLine",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -744,
            name: "hashMarkTop0",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -744,
            name: "hashMarkBottom0",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -713,
            name: "hashMarkTop1",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -713,
            name: "hashMarkBottom1",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -682,
            name: "hashMarkTop2",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -682,
            name: "hashMarkBottom2",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -651,
            name: "hashMarkTop3",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -651,
            name: "hashMarkBottom3",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -589,
            name: "hashMarkTop4",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -589,
            name: "hashMarkBottom4",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -558,
            name: "hashMarkTop5",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -558,
            name: "hashMarkBottom5",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -527,
            name: "hashMarkTop6",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -527,
            name: "hashMarkBottom6",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -496,
            name: "hashMarkTop7",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -496,
            name: "hashMarkBottom7",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -434,
            name: "hashMarkTop8",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -434,
            name: "hashMarkBottom8",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -403,
            name: "hashMarkTop9",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -403,
            name: "hashMarkBottom9",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -372,
            name: "hashMarkTop10",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -372,
            name: "hashMarkBottom10",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -341,
            name: "hashMarkTop11",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -341,
            name: "hashMarkBottom11",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -279,
            name: "hashMarkTop12",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -279,
            name: "hashMarkBottom12",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -248,
            name: "hashMarkTop13",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -248,
            name: "hashMarkBottom13",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -217,
            name: "hashMarkTop14",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -217,
            name: "hashMarkBottom14",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -186,
            name: "hashMarkTop15",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -186,
            name: "hashMarkBottom15",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -124,
            name: "hashMarkTop16",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -124,
            name: "hashMarkBottom16",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -93,
            name: "hashMarkTop17",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -93,
            name: "hashMarkBottom17",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -62,
            name: "hashMarkTop18",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -62,
            name: "hashMarkBottom18",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: -31,
            name: "hashMarkTop19",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: -31,
            name: "hashMarkBottom19",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 31,
            name: "hashMarkTop20",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 31,
            name: "hashMarkBottom20",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 62,
            name: "hashMarkTop21",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 62,
            name: "hashMarkBottom21",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 93,
            name: "hashMarkTop22",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 93,
            name: "hashMarkBottom22",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 124,
            name: "hashMarkTop23",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 124,
            name: "hashMarkBottom23",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 186,
            name: "hashMarkTop24",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 186,
            name: "hashMarkBottom24",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 217,
            name: "hashMarkTop25",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 217,
            name: "hashMarkBottom25",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 248,
            name: "hashMarkTop26",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 248,
            name: "hashMarkBottom26",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 279,
            name: "hashMarkTop27",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 279,
            name: "hashMarkBottom27",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 341,
            name: "hashMarkTop28",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 341,
            name: "hashMarkBottom28",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 372,
            name: "hashMarkTop29",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 372,
            name: "hashMarkBottom29",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 403,
            name: "hashMarkTop30",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 403,
            name: "hashMarkBottom30",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 434,
            name: "hashMarkTop31",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 434,
            name: "hashMarkBottom31",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 496,
            name: "hashMarkTop32",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 496,
            name: "hashMarkBottom32",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 527,
            name: "hashMarkTop33",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 527,
            name: "hashMarkBottom33",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 558,
            name: "hashMarkTop34",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 558,
            name: "hashMarkBottom34",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 589,
            name: "hashMarkTop35",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 589,
            name: "hashMarkBottom35",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 651,
            name: "hashMarkTop36",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 651,
            name: "hashMarkBottom36",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 682,
            name: "hashMarkTop37",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 682,
            name: "hashMarkBottom37",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 713,
            name: "hashMarkTop38",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 713,
            name: "hashMarkBottom38",
        }),
        vLine({
            extend: HASH_MARK_TOP_BASE,
            x: 744,
            name: "hashMarkTop39",
        }),
        vLine({
            extend: HASH_MARK_BOTTOM_BASE,
            x: 744,
            name: "hashMarkBottom39",
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: -697.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: -697.5,
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: -542.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: -542.5,
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: -387.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: -387.5,
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: -232.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: -232.5,
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: -77.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: -77.5,
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: 77.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: 77.5,
        }),
        vLine({
            extend: [TICK_MARK_TOP_BASE, TICK_MARK_GREEN_SEGMENT],
            x: 232.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: 232.5,
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: 387.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: 387.5,
        }),
        vLine({
            extend: [TICK_MARK_TOP_BASE, TICK_MARK_GREEN_SEGMENT],
            x: 542.5,
        }),
        vLine({
            extend: TICK_MARK_BOTTOM_BASE,
            x: 542.5,
        }),
        vLine({
            extend: TICK_MARK_TOP_BASE,
            x: 697.5,
        }),
        vLine({
            extend: [TICK_MARK_BOTTOM_BASE, TICK_MARK_GREEN_SEGMENT],
            x: 697.5,
        }),
        vLine({
            extend: GOAL_POST_VERTICAL_BASE,
            x: -930,
        }),
        vLine({
            extend: GOAL_POST_VERTICAL_BASE,
            x: 930,
        }),
        line({
            extend: GOAL_POST_LINE_BASE,
            from: { x: -930, y: -60 },
            to: { x: -980, y: -130 },
        }),
        line({
            extend: GOAL_POST_LINE_BASE,
            from: { x: -930, y: 60 },
            to: { x: -990, y: -10 },
        }),
        line({
            extend: GOAL_POST_LINE_BASE,
            from: { x: 930, y: -60 },
            to: { x: 980, y: -130 },
        }),
        line({
            extend: GOAL_POST_LINE_BASE,
            from: { x: 930, y: 60 },
            to: { x: 990, y: -10 },
        }),
        vLine({
            extend: BALL_BOUNDARY_LEFT_BASE,
            x: -1005,
        }),
        vLine({
            extend: BALL_BOUNDARY_RIGHT_BASE,
            x: 1005,
        }),
    ],
    planes: [
        {
            rect: { x: [-1065, 1065], y: [-350, 350] },
            side: "outside",
            props: { cMask: ["ball"] },
        },
        {
            rect: { x: [-1090, 1090], y: [-375, 375] },
            side: "outside",
            props: { bCoef: 0.9 },
        },
        {
            line: "leftGoalLine",
            side: "right",
            props: { cMask: ["c0"] },
        },
        {
            line: "rightGoalLine",
            side: "left",
            props: { cMask: ["c1"] },
        },
        {
            normal: [-1, 0],
            dist: 0,
            cMask: ["c2"],
        },
        {
            normal: [1, 0],
            dist: 0,
            cMask: ["c3"],
        },
    ],
    discs: [
        {
            radius: 4,
            invMass: 0,
            pos: pos(930, -60),
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: pos(-930, -60),
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: pos(-930, 60),
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: pos(930, 60),
            color: "FFFF00",
        },
        ...repeat(28, {
            radius: 0,
            invMass: 1,
            pos: pos(0, 0),
            color: "transparent",
            cGroup: [],
        }),
        ...repeat(4, {
            radius: 1,
            invMass: 1,
            pos: pos(9999, 9999),
            color: "FF0000",
            cGroup: [],
        }),
        ...repeat(12, {
            radius: 0,
            invMass: 1,
            pos: pos(0, 0),
            color: "transparent",
            cGroup: [],
        }),
        ...repeat(2, {
            radius: 1,
            invMass: 1,
            pos: pos(9999, 9999),
            color: "F5F5F5",
            cGroup: [],
        }),
        ...repeat(2, {
            radius: 7.125,
            invMass: 0,
            pos: pos(2000, 2000),
            color: "FFAA00",
            cGroup: [],
            cMask: [],
        }),
        ...repeat(3, {
            radius: 1,
            invMass: 1,
            pos: pos(9999, 9999),
            color: "F5F5F5",
            cGroup: [],
        }),
        ...repeat(4, {
            radius: 0,
            invMass: 1,
            pos: pos(0, 0),
            color: "transparent",
            cGroup: [],
        }),
    ],
    anchors: [
        ...anchorsFromPairs({ prefix: "orange", pairs: pairList([4, 5]) }),
        ...anchorsFromPairs({ prefix: "blue", pairs: pairList([6, 7]) }),
        ...anchorsFromPairs({ prefix: "ball", pairs: pairList([49, 50]) }),
        ...anchorsFromPairs({
            prefix: "red",
            pairs: pairedIndexes({ start: 8, count: 12 }),
        }),
        ...anchorsFromPairs({
            prefix: "white",
            pairs: pairedIndexes({ start: 36, count: 6 }),
        }),
        ...anchorsFromPairs({
            prefix: "tail",
            pairs: pairList([55, 56], [57, 58]),
        }),
        { name: "outerCrowdingCorner0", index: 32 },
        { name: "outerCrowdingCorner1", index: 33 },
        { name: "outerCrowdingCorner2", index: 34 },
        { name: "outerCrowdingCorner3", index: 35 },
        { name: "innerCrowdingCorner0", index: 48 },
        { name: "innerCrowdingCorner1", index: 52 },
        { name: "innerCrowdingCorner2", index: 53 },
        { name: "innerCrowdingCorner3", index: 54 },
    ],
    joints: [
        ...jointsFromPairs({
            prefix: "orange",
            pairs: pairList([4, 5]),
            color: "FF9912",
        }),
        ...jointsFromPairs({
            prefix: "blue",
            pairs: pairList([6, 7]),
            color: "3E67CF",
        }),
        ...jointsFromPairs({
            prefix: "ball",
            pairs: pairList([49, 50]),
            color: "FFAA00",
        }),
        ...jointsFromPairs({
            prefix: "red",
            pairs: pairedIndexes({ start: 8, count: 12 }),
            color: "FF0000",
        }),
        ...jointsFromPairs({
            prefix: "white",
            pairs: pairedIndexes({ start: 36, count: 6 }),
            color: "F5F5F5",
        }),
        ...jointsFromPairs({
            prefix: "tail",
            pairs: pairList([55, 56], [57, 58]),
            color: "F5F5F5",
        }),
    ],
} satisfies StadiumSchema;

export const classicStadiumObjectOutput: StadiumObject = {
    name: "BFL (Classic)",
    canBeStored: false,
    width: 1090,
    height: 395,
    bg: {
        type: "grass",
        width: 930,
        height: 266,
    },
    goals: [
        {
            p0: [-1065, 0],
            p1: [-1005, 0],
            team: "blue",
        },
        {
            p0: [1006.9833374023, 1.6000061035156],
            p1: [1063.9833374023, 1.6000061035156],
            team: "red",
        },
    ],
    playerPhysics: {
        bCoef: 0.5,
        invMass: 1e26,
        kickStrength: 7,
    },
    ballPhysics: {
        radius: 7.125,
        bCoef: 0.5,
        cMask: ["red", "blue", "wall"],
        color: "631515",
        cGroup: ["ball", "kick", "score"],
    },
    cameraFollow: "player",
    spawnDistance: 980,
    traits: {},
    redSpawnPoints: [],
    blueSpawnPoints: [],
    vertexes: [
        {
            x: 0,
            y: 334,
            bCoef: 0.1,
            cMask: ["red", "blue"],
        },
        {
            x: 0,
            y: -330,
            bCoef: 0.1,
            cMask: ["red", "blue"],
        },
        {
            x: -775,
            y: -375,
            cMask: [],
        },
        {
            x: -775,
            y: 375,
            cMask: [],
        },
        {
            x: 775,
            y: -375,
            cMask: [],
        },
        {
            x: 775,
            y: 375,
            cMask: [],
        },
        {
            x: -775,
            y: -266,
            cMask: [],
        },
        {
            x: -775,
            y: 266,
            cMask: [],
        },
        {
            x: -620,
            y: -266,
            cMask: [],
        },
        {
            x: -620,
            y: 266,
            cMask: [],
        },
        {
            x: -465,
            y: -266,
            cMask: [],
        },
        {
            x: -465,
            y: 266,
            cMask: [],
        },
        {
            x: -310,
            y: -266,
            cMask: [],
        },
        {
            x: -310,
            y: 266,
            cMask: [],
        },
        {
            x: -155,
            y: -266,
            cMask: [],
        },
        {
            x: -155,
            y: 266,
            cMask: [],
        },
        {
            x: 155,
            y: -266,
            cMask: [],
        },
        {
            x: 155,
            y: 266,
            cMask: [],
        },
        {
            x: 310,
            y: -266,
            cMask: [],
        },
        {
            x: 310,
            y: 266,
            cMask: [],
        },
        {
            x: 465,
            y: -266,
            cMask: [],
        },
        {
            x: 465,
            y: 266,
            cMask: [],
        },
        {
            x: 620,
            y: -266,
            cMask: [],
        },
        {
            x: 620,
            y: 266,
            cMask: [],
        },
        {
            x: 775,
            y: -266,
            cMask: [],
        },
        {
            x: 775,
            y: 266,
            cMask: [],
        },
        {
            x: 0,
            y: -266,
            cMask: [],
        },
        {
            x: 0,
            y: 266,
            cMask: [],
        },
        {
            x: -744,
            y: 80,
            cMask: [],
        },
        {
            x: -744,
            y: 60,
            cMask: [],
        },
        {
            x: -744,
            y: -60,
            cMask: [],
        },
        {
            x: -744,
            y: -80,
            cMask: [],
        },
        {
            x: -713,
            y: 80,
            cMask: [],
        },
        {
            x: -713,
            y: 60,
            cMask: [],
        },
        {
            x: -713,
            y: -60,
            cMask: [],
        },
        {
            x: -713,
            y: -80,
            cMask: [],
        },
        {
            x: -682,
            y: 80,
            cMask: [],
        },
        {
            x: -682,
            y: 60,
            cMask: [],
        },
        {
            x: -682,
            y: -60,
            cMask: [],
        },
        {
            x: -682,
            y: -80,
            cMask: [],
        },
        {
            x: -651,
            y: 80,
            cMask: [],
        },
        {
            x: -651,
            y: 60,
            cMask: [],
        },
        {
            x: -651,
            y: -60,
            cMask: [],
        },
        {
            x: -651,
            y: -80,
            cMask: [],
        },
        {
            x: -589,
            y: 80,
            cMask: [],
        },
        {
            x: -589,
            y: 60,
            cMask: [],
        },
        {
            x: -589,
            y: -60,
            cMask: [],
        },
        {
            x: -589,
            y: -80,
            cMask: [],
        },
        {
            x: -558,
            y: 80,
            cMask: [],
        },
        {
            x: -558,
            y: 60,
            cMask: [],
        },
        {
            x: -558,
            y: -60,
            cMask: [],
        },
        {
            x: -558,
            y: -80,
            cMask: [],
        },
        {
            x: -527,
            y: 80,
            cMask: [],
        },
        {
            x: -527,
            y: 60,
            cMask: [],
        },
        {
            x: -527,
            y: -60,
            cMask: [],
        },
        {
            x: -527,
            y: -80,
            cMask: [],
        },
        {
            x: -496,
            y: 80,
            cMask: [],
        },
        {
            x: -496,
            y: 60,
            cMask: [],
        },
        {
            x: -496,
            y: -60,
            cMask: [],
        },
        {
            x: -496,
            y: -80,
            cMask: [],
        },
        {
            x: -434,
            y: 80,
            cMask: [],
        },
        {
            x: -434,
            y: 60,
            cMask: [],
        },
        {
            x: -434,
            y: -60,
            cMask: [],
        },
        {
            x: -434,
            y: -80,
            cMask: [],
        },
        {
            x: -403,
            y: 80,
            cMask: [],
        },
        {
            x: -403,
            y: 60,
            cMask: [],
        },
        {
            x: -403,
            y: -60,
            cMask: [],
        },
        {
            x: -403,
            y: -80,
            cMask: [],
        },
        {
            x: -372,
            y: 80,
            cMask: [],
        },
        {
            x: -372,
            y: 60,
            cMask: [],
        },
        {
            x: -372,
            y: -60,
            cMask: [],
        },
        {
            x: -372,
            y: -80,
            cMask: [],
        },
        {
            x: -341,
            y: 80,
            cMask: [],
        },
        {
            x: -341,
            y: 60,
            cMask: [],
        },
        {
            x: -341,
            y: -60,
            cMask: [],
        },
        {
            x: -341,
            y: -80,
            cMask: [],
        },
        {
            x: -279,
            y: 80,
            cMask: [],
        },
        {
            x: -279,
            y: 60,
            cMask: [],
        },
        {
            x: -279,
            y: -60,
            cMask: [],
        },
        {
            x: -279,
            y: -80,
            cMask: [],
        },
        {
            x: -248,
            y: 80,
            cMask: [],
        },
        {
            x: -248,
            y: 60,
            cMask: [],
        },
        {
            x: -248,
            y: -60,
            cMask: [],
        },
        {
            x: -248,
            y: -80,
            cMask: [],
        },
        {
            x: -217,
            y: 80,
            cMask: [],
        },
        {
            x: -217,
            y: 60,
            cMask: [],
        },
        {
            x: -217,
            y: -60,
            cMask: [],
        },
        {
            x: -217,
            y: -80,
            cMask: [],
        },
        {
            x: -186,
            y: 80,
            cMask: [],
        },
        {
            x: -186,
            y: 60,
            cMask: [],
        },
        {
            x: -186,
            y: -60,
            cMask: [],
        },
        {
            x: -186,
            y: -80,
            cMask: [],
        },
        {
            x: -124,
            y: 80,
            cMask: [],
        },
        {
            x: -124,
            y: 60,
            cMask: [],
        },
        {
            x: -124,
            y: -60,
            cMask: [],
        },
        {
            x: -124,
            y: -80,
            cMask: [],
        },
        {
            x: -93,
            y: 80,
            cMask: [],
        },
        {
            x: -93,
            y: 60,
            cMask: [],
        },
        {
            x: -93,
            y: -60,
            cMask: [],
        },
        {
            x: -93,
            y: -80,
            cMask: [],
        },
        {
            x: -62,
            y: 80,
            cMask: [],
        },
        {
            x: -62,
            y: 60,
            cMask: [],
        },
        {
            x: -62,
            y: -60,
            cMask: [],
        },
        {
            x: -62,
            y: -80,
            cMask: [],
        },
        {
            x: -31,
            y: 80,
            cMask: [],
        },
        {
            x: -31,
            y: 60,
            cMask: [],
        },
        {
            x: -31,
            y: -60,
            cMask: [],
        },
        {
            x: -31,
            y: -80,
            cMask: [],
        },
        {
            x: 31,
            y: 80,
            cMask: [],
        },
        {
            x: 31,
            y: 60,
            cMask: [],
        },
        {
            x: 31,
            y: -60,
            cMask: [],
        },
        {
            x: 31,
            y: -80,
            cMask: [],
        },
        {
            x: 62,
            y: 80,
            cMask: [],
        },
        {
            x: 62,
            y: 60,
            cMask: [],
        },
        {
            x: 62,
            y: -60,
            cMask: [],
        },
        {
            x: 62,
            y: -80,
            cMask: [],
        },
        {
            x: 93,
            y: 80,
            cMask: [],
        },
        {
            x: 93,
            y: 60,
            cMask: [],
        },
        {
            x: 93,
            y: -60,
            cMask: [],
        },
        {
            x: 93,
            y: -80,
            cMask: [],
        },
        {
            x: 124,
            y: 80,
            cMask: [],
        },
        {
            x: 124,
            y: 60,
            cMask: [],
        },
        {
            x: 124,
            y: -60,
            cMask: [],
        },
        {
            x: 124,
            y: -80,
            cMask: [],
        },
        {
            x: 186,
            y: 80,
            cMask: [],
        },
        {
            x: 186,
            y: 60,
            cMask: [],
        },
        {
            x: 186,
            y: -60,
            cMask: [],
        },
        {
            x: 186,
            y: -80,
            cMask: [],
        },
        {
            x: 217,
            y: 80,
            cMask: [],
        },
        {
            x: 217,
            y: 60,
            cMask: [],
        },
        {
            x: 217,
            y: -60,
            cMask: [],
        },
        {
            x: 217,
            y: -80,
            cMask: [],
        },
        {
            x: 248,
            y: 80,
            cMask: [],
        },
        {
            x: 248,
            y: 60,
            cMask: [],
        },
        {
            x: 248,
            y: -60,
            cMask: [],
        },
        {
            x: 248,
            y: -80,
            cMask: [],
        },
        {
            x: 279,
            y: 80,
            cMask: [],
        },
        {
            x: 279,
            y: 60,
            cMask: [],
        },
        {
            x: 279,
            y: -60,
            cMask: [],
        },
        {
            x: 279,
            y: -80,
            cMask: [],
        },
        {
            x: 341,
            y: 80,
            cMask: [],
        },
        {
            x: 341,
            y: 60,
            cMask: [],
        },
        {
            x: 341,
            y: -60,
            cMask: [],
        },
        {
            x: 341,
            y: -80,
            cMask: [],
        },
        {
            x: 372,
            y: 80,
            cMask: [],
        },
        {
            x: 372,
            y: 60,
            cMask: [],
        },
        {
            x: 372,
            y: -60,
            cMask: [],
        },
        {
            x: 372,
            y: -80,
            cMask: [],
        },
        {
            x: 403,
            y: 80,
            cMask: [],
        },
        {
            x: 403,
            y: 60,
            cMask: [],
        },
        {
            x: 403,
            y: -60,
            cMask: [],
        },
        {
            x: 403,
            y: -80,
            cMask: [],
        },
        {
            x: 434,
            y: 80,
            cMask: [],
        },
        {
            x: 434,
            y: 60,
            cMask: [],
        },
        {
            x: 434,
            y: -60,
            cMask: [],
        },
        {
            x: 434,
            y: -80,
            cMask: [],
        },
        {
            x: 496,
            y: 80,
            cMask: [],
        },
        {
            x: 496,
            y: 60,
            cMask: [],
        },
        {
            x: 496,
            y: -60,
            cMask: [],
        },
        {
            x: 496,
            y: -80,
            cMask: [],
        },
        {
            x: 527,
            y: 80,
            cMask: [],
        },
        {
            x: 527,
            y: 60,
            cMask: [],
        },
        {
            x: 527,
            y: -60,
            cMask: [],
        },
        {
            x: 527,
            y: -80,
            cMask: [],
        },
        {
            x: 558,
            y: 80,
            cMask: [],
        },
        {
            x: 558,
            y: 60,
            cMask: [],
        },
        {
            x: 558,
            y: -60,
            cMask: [],
        },
        {
            x: 558,
            y: -80,
            cMask: [],
        },
        {
            x: 589,
            y: 80,
            cMask: [],
        },
        {
            x: 589,
            y: 60,
            cMask: [],
        },
        {
            x: 589,
            y: -60,
            cMask: [],
        },
        {
            x: 589,
            y: -80,
            cMask: [],
        },
        {
            x: 651,
            y: 80,
            cMask: [],
        },
        {
            x: 651,
            y: 60,
            cMask: [],
        },
        {
            x: 651,
            y: -60,
            cMask: [],
        },
        {
            x: 651,
            y: -80,
            cMask: [],
        },
        {
            x: 682,
            y: 80,
            cMask: [],
        },
        {
            x: 682,
            y: 60,
            cMask: [],
        },
        {
            x: 682,
            y: -60,
            cMask: [],
        },
        {
            x: 682,
            y: -80,
            cMask: [],
        },
        {
            x: 713,
            y: 80,
            cMask: [],
        },
        {
            x: 713,
            y: 60,
            cMask: [],
        },
        {
            x: 713,
            y: -60,
            cMask: [],
        },
        {
            x: 713,
            y: -80,
            cMask: [],
        },
        {
            x: 744,
            y: 80,
            cMask: [],
        },
        {
            x: 744,
            y: 60,
            cMask: [],
        },
        {
            x: 744,
            y: -60,
            cMask: [],
        },
        {
            x: 744,
            y: -80,
            cMask: [],
        },
        {
            x: -697.5,
            y: 266,
            cMask: [],
        },
        {
            x: -697.5,
            y: 241,
            cMask: [],
        },
        {
            x: -697.5,
            y: -241,
            cMask: [],
        },
        {
            x: -697.5,
            y: -266,
            cMask: [],
        },
        {
            x: -542.5,
            y: 266,
            cMask: [],
        },
        {
            x: -542.5,
            y: 241,
            cMask: [],
        },
        {
            x: -542.5,
            y: -241,
            cMask: [],
        },
        {
            x: -542.5,
            y: -266,
            cMask: [],
        },
        {
            x: -387.5,
            y: 266,
            cMask: [],
        },
        {
            x: -387.5,
            y: 241,
            cMask: [],
        },
        {
            x: -387.5,
            y: -241,
            cMask: [],
        },
        {
            x: -387.5,
            y: -266,
            cMask: [],
        },
        {
            x: -232.5,
            y: 266,
            cMask: [],
        },
        {
            x: -232.5,
            y: 241,
            cMask: [],
        },
        {
            x: -232.5,
            y: -241,
            cMask: [],
        },
        {
            x: -232.5,
            y: -266,
            cMask: [],
        },
        {
            x: -77.5,
            y: 266,
            cMask: [],
        },
        {
            x: -77.5,
            y: 241,
            cMask: [],
        },
        {
            x: -77.5,
            y: -241,
            cMask: [],
        },
        {
            x: -77.5,
            y: -266,
            cMask: [],
        },
        {
            x: 77.5,
            y: 266,
            cMask: [],
        },
        {
            x: 77.5,
            y: 241,
            cMask: [],
        },
        {
            x: 77.5,
            y: -241,
            cMask: [],
        },
        {
            x: 77.5,
            y: -266,
            cMask: [],
        },
        {
            x: 232.5,
            y: 266,
            cMask: [],
        },
        {
            x: 232.5,
            y: 241,
            cMask: [],
        },
        {
            x: 232.5,
            y: -241,
            cMask: [],
        },
        {
            x: 232.5,
            y: -266,
            cMask: [],
        },
        {
            x: 387.5,
            y: 266,
            cMask: [],
        },
        {
            x: 387.5,
            y: 241,
            cMask: [],
        },
        {
            x: 387.5,
            y: -241,
            cMask: [],
        },
        {
            x: 387.5,
            y: -266,
            cMask: [],
        },
        {
            x: 542.5,
            y: 266,
            cMask: [],
        },
        {
            x: 542.5,
            y: 241,
            cMask: [],
        },
        {
            x: 542.5,
            y: -241,
            cMask: [],
        },
        {
            x: 542.5,
            y: -266,
            cMask: [],
        },
        {
            x: 697.5,
            y: 266,
            cMask: [],
        },
        {
            x: 697.5,
            y: 241,
            cMask: [],
        },
        {
            x: 697.5,
            y: -241,
            cMask: [],
        },
        {
            x: 697.5,
            y: -266,
            cMask: [],
        },
        {
            x: -930,
            y: -60,
            cMask: [],
        },
        {
            x: -930,
            y: 60,
            cMask: [],
        },
        {
            x: 930,
            y: -60,
            cMask: [],
        },
        {
            x: 930,
            y: 60,
            cMask: [],
        },
        {
            x: -980,
            y: -130,
            cMask: [],
        },
        {
            x: -990,
            y: -10,
            cMask: [],
        },
        {
            x: 980,
            y: -130,
            cMask: [],
        },
        {
            x: 990,
            y: -10,
            cMask: [],
        },
        {
            x: -1005,
            y: 360,
        },
        {
            x: -1005,
            y: -360,
        },
        {
            x: 1005,
            y: 360,
        },
        {
            x: 1005,
            y: -360,
        },
        {
            x: -930,
            y: -266,
            cMask: [],
        },
        {
            x: 930,
            y: -266,
            cMask: [],
        },
        {
            x: 930,
            y: 266,
            cMask: [],
        },
        {
            x: -930,
            y: 266,
            cMask: [],
        },
    ],
    segments: [
        {
            v0: 0,
            v1: 1,
            vis: false,
            bCoef: 0.1,
            cMask: ["red", "blue"],
            cGroup: [],
        },
        {
            v0: 2,
            v1: 3,
            vis: false,
            color: "FFEA00",
            bCoef: 0.1,
            cMask: ["red", "blue"],
            cGroup: [],
        },
        {
            v0: 4,
            v1: 5,
            vis: false,
            color: "FFEA00",
            bCoef: 0.1,
            cMask: ["red", "blue"],
            cGroup: [],
        },
        {
            v0: 6,
            v1: 7,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 8,
            v1: 9,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 10,
            v1: 11,
            color: "D0312D",
            cMask: [],
        },
        {
            v0: 12,
            v1: 13,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 14,
            v1: 15,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 16,
            v1: 17,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 18,
            v1: 19,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 20,
            v1: 21,
            color: "D0312D",
            cMask: [],
        },
        {
            v0: 22,
            v1: 23,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 24,
            v1: 25,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 26,
            v1: 27,
            color: "ACDE97",
            cMask: [],
        },
        {
            v0: 28,
            v1: 29,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 30,
            v1: 31,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 32,
            v1: 33,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 34,
            v1: 35,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 36,
            v1: 37,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 38,
            v1: 39,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 40,
            v1: 41,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 42,
            v1: 43,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 44,
            v1: 45,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 46,
            v1: 47,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 48,
            v1: 49,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 50,
            v1: 51,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 52,
            v1: 53,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 54,
            v1: 55,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 56,
            v1: 57,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 58,
            v1: 59,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 60,
            v1: 61,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 62,
            v1: 63,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 64,
            v1: 65,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 66,
            v1: 67,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 68,
            v1: 69,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 70,
            v1: 71,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 72,
            v1: 73,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 74,
            v1: 75,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 76,
            v1: 77,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 78,
            v1: 79,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 80,
            v1: 81,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 82,
            v1: 83,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 84,
            v1: 85,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 86,
            v1: 87,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 88,
            v1: 89,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 90,
            v1: 91,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 92,
            v1: 93,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 94,
            v1: 95,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 96,
            v1: 97,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 98,
            v1: 99,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 100,
            v1: 101,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 102,
            v1: 103,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 104,
            v1: 105,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 106,
            v1: 107,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 108,
            v1: 109,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 110,
            v1: 111,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 112,
            v1: 113,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 114,
            v1: 115,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 116,
            v1: 117,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 118,
            v1: 119,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 120,
            v1: 121,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 122,
            v1: 123,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 124,
            v1: 125,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 126,
            v1: 127,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 128,
            v1: 129,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 130,
            v1: 131,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 132,
            v1: 133,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 134,
            v1: 135,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 136,
            v1: 137,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 138,
            v1: 139,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 140,
            v1: 141,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 142,
            v1: 143,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 144,
            v1: 145,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 146,
            v1: 147,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 148,
            v1: 149,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 150,
            v1: 151,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 152,
            v1: 153,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 154,
            v1: 155,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 156,
            v1: 157,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 158,
            v1: 159,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 160,
            v1: 161,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 162,
            v1: 163,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 164,
            v1: 165,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 166,
            v1: 167,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 168,
            v1: 169,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 170,
            v1: 171,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 172,
            v1: 173,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 174,
            v1: 175,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 176,
            v1: 177,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 178,
            v1: 179,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 180,
            v1: 181,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 182,
            v1: 183,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 184,
            v1: 185,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 186,
            v1: 187,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 188,
            v1: 189,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 190,
            v1: 191,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 192,
            v1: 193,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 194,
            v1: 195,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 196,
            v1: 197,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 198,
            v1: 199,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 200,
            v1: 201,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 202,
            v1: 203,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 204,
            v1: 205,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 206,
            v1: 207,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 208,
            v1: 209,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 210,
            v1: 211,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 212,
            v1: 213,
            color: "C7E6BD",
            cMask: [],
        },
        {
            v0: 214,
            v1: 215,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 216,
            v1: 217,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 218,
            v1: 219,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 220,
            v1: 221,
            color: "C7E6BD",
            cMask: [],
        },
        {
            v0: 222,
            v1: 223,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 224,
            v1: 225,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 226,
            v1: 227,
            color: "C7E6BD",
            cMask: [],
        },
        {
            v0: 228,
            v1: 229,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 230,
            v1: 231,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 228,
            v1: 232,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 229,
            v1: 233,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 230,
            v1: 234,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 231,
            v1: 235,
            color: "FFEA00",
            cMask: [],
        },
        {
            v0: 236,
            v1: 237,
            vis: false,
            color: "0000FF",
            cMask: ["ball"],
        },
        {
            v0: 238,
            v1: 239,
            vis: false,
            color: "D0312D",
            cMask: ["ball"],
        },
        {
            v0: 240,
            v1: 241,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 241,
            v1: 242,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 242,
            v1: 243,
            color: "FFFFFF",
            cMask: [],
        },
        {
            v0: 243,
            v1: 240,
            color: "FFFFFF",
            cMask: [],
        },
    ],
    planes: [
        {
            normal: [1, 0],
            dist: -1065,
            cMask: ["ball"],
        },
        {
            normal: [-1, 0],
            dist: -1065,
            cMask: ["ball"],
        },
        {
            normal: [0, 1],
            dist: -350,
            cMask: ["ball"],
        },
        {
            normal: [0, -1],
            dist: -350,
            cMask: ["ball"],
        },
        {
            normal: [1, 0],
            dist: -1090,
            bCoef: 0.9,
        },
        {
            normal: [-1, 0],
            dist: -1090,
            bCoef: 0.9,
        },
        {
            normal: [0, 1],
            dist: -375,
            bCoef: 0.9,
        },
        {
            normal: [0, -1],
            dist: -375,
            bCoef: 0.9,
        },
        {
            normal: [-1, 0],
            dist: 775,
            cMask: ["c0"],
        },
        {
            normal: [1, 0],
            dist: 775,
            cMask: ["c1"],
        },
        {
            normal: [-1, 0],
            dist: 0,
            cMask: ["c2"],
        },
        {
            normal: [1, 0],
            dist: 0,
            cMask: ["c3"],
        },
    ],
    discs: [
        {
            radius: 4,
            invMass: 0,
            pos: [930, -60],
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: [-930, -60],
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: [-930, 60],
            color: "FFFF00",
        },
        {
            radius: 4,
            invMass: 0,
            pos: [930, 60],
            color: "FFFF00",
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "FF0000",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "FF0000",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "FF0000",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "FF0000",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "F5F5F5",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "F5F5F5",
            cGroup: [],
        },
        {
            radius: 7.125,
            invMass: 0,
            pos: [2000, 2000],
            color: "FFAA00",
            cGroup: [],
            cMask: [],
        },
        {
            radius: 7.125,
            invMass: 0,
            pos: [2000, 2000],
            color: "FFAA00",
            cGroup: [],
            cMask: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "F5F5F5",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "F5F5F5",
            cGroup: [],
        },
        {
            radius: 1,
            invMass: 1,
            pos: [9999, 9999],
            color: "F5F5F5",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
        {
            radius: 0,
            invMass: 1,
            pos: [0, 0],
            color: "transparent",
            cGroup: [],
        },
    ],
    joints: [
        {
            d0: 5,
            d1: 6,
            color: "FF9912",
            length: [0, 99999],
        },
        {
            d0: 7,
            d1: 8,
            color: "3E67CF",
            length: [0, 99999],
        },
        {
            d0: 50,
            d1: 51,
            color: "FFAA00",
            length: [0, 99999],
        },
        {
            d0: 9,
            d1: 10,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 11,
            d1: 12,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 13,
            d1: 14,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 15,
            d1: 16,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 17,
            d1: 18,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 19,
            d1: 20,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 21,
            d1: 22,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 23,
            d1: 24,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 25,
            d1: 26,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 27,
            d1: 28,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 29,
            d1: 30,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 31,
            d1: 32,
            color: "FF0000",
            length: [0, 99999],
        },
        {
            d0: 37,
            d1: 38,
            color: "F5F5F5",
            length: [0, 99999],
        },
        {
            d0: 39,
            d1: 40,
            color: "F5F5F5",
            length: [0, 99999],
        },
        {
            d0: 41,
            d1: 42,
            color: "F5F5F5",
            length: [0, 99999],
        },
        {
            d0: 43,
            d1: 44,
            color: "F5F5F5",
            length: [0, 99999],
        },
        {
            d0: 45,
            d1: 46,
            color: "F5F5F5",
            length: [0, 99999],
        },
        {
            d0: 47,
            d1: 48,
            color: "F5F5F5",
            length: [0, 99999],
        },
        {
            d0: 56,
            d1: 57,
            color: "F5F5F5",
            length: [0, 99999],
        },
        {
            d0: 58,
            d1: 59,
            color: "F5F5F5",
            length: [0, 99999],
        },
    ],
};

export default classicStadiumObjectOutput;
